import { buildExportDimensions } from '../playExportModel';
import { buildExportRangeData } from '../playExportRange';

export const buildExportRenderRequest = ({
  snapshot,
  exportView,
  selectedExportPlayer,
  exportPlayerDisplayName,
  captionText,
  teamLogos,
  leftMargin,
  rightMargin,
  playRef,
  gameDate,
  displayAwayTeamNames,
  displayHomeTeamNames,
  displayAwayPlayers,
  displayAwayPlayersAll,
  displayHomePlayers,
  displayHomePlayersAll,
  displayAwayPlayerTimeline,
  displayHomePlayerTimeline,
  displayScoreTimeline,
  displayLastAction,
  gameStatus,
  isFinal,
  numPeriods,
  timelineWindow,
  showScoreDiff,
  statOn,
  teamColors,
  awayColor,
  homeColor,
}) => {
  const {
    exportRangeSnapshot,
    exportRangeLabel,
    legendShouldWrap,
    endAtLastScore,
    exportIsFullGameRange,
  } = snapshot;

  const {
    durationRatio,
    exportAwayPlayers,
    exportAwayPlayerTimeline,
    exportEndAtSeconds,
    exportHomePlayers,
    exportHomePlayerTimeline,
    exportScoreStats,
    exportScoreTimeline,
    exportStartScoreDiff,
    exportStatusLabel,
    exportTimelineWindow,
  } = buildExportRangeData({
    displayAwayPlayers,
    displayAwayPlayerTimeline,
    displayHomePlayers,
    displayHomePlayerTimeline,
    displayLastAction,
    displayScoreTimeline,
    exportRangeSnapshot,
    gameStatus,
    isFinal,
    numPeriods,
    timelineWindow,
  });

  const { exportAwayPlayers: exportAwayPlayersAll, exportHomePlayers: exportHomePlayersAll } =
    buildExportRangeData({
      displayAwayPlayers: displayAwayPlayersAll || displayAwayPlayers,
      displayAwayPlayerTimeline,
      displayHomePlayers: displayHomePlayersAll || displayHomePlayers,
      displayHomePlayerTimeline,
      displayLastAction,
      displayScoreTimeline,
      exportRangeSnapshot,
      gameStatus,
      isFinal,
      numPeriods,
      timelineWindow,
    });

  const { exportWidth } = buildExportDimensions({
    exportView,
    isFullGameRange: exportIsFullGameRange,
    durationRatio,
  });

  return {
    exportRangeLabel,
    exportIsFullGameRange,
    renderInput: {
      exportView,
      selectedPlayer: selectedExportPlayer,
      playerDisplayName: exportPlayerDisplayName,
      captionText: String(captionText || ''),
      teamLogos: teamLogos || null,
      exportWidth,
      legendShouldWrap,
      rangeLabel: exportRangeLabel,
      periodRange: exportRangeSnapshot,
      leftMargin,
      rightMargin,
      playRef,
      gameDate,
      displayAwayTeamNames,
      displayHomeTeamNames,
      filteredAwayPlayers: exportAwayPlayers,
      filteredHomePlayers: exportHomePlayers,
      boxScoreAwayPlayers: exportAwayPlayersAll,
      boxScoreHomePlayers: exportHomePlayersAll,
      filteredAwayPlayerTimeline: exportAwayPlayerTimeline,
      filteredHomePlayerTimeline: exportHomePlayerTimeline,
      filteredScoreTimeline: exportScoreTimeline,
      displayScoreTimeline,
      statusLabel: exportStatusLabel,
      endAtLastScore,
      endAtSeconds: exportEndAtSeconds,
      startScoreDiff: exportStartScoreDiff,
      timelineWindow: exportTimelineWindow,
      maxY: exportScoreStats.maxY,
      maxLead: exportScoreStats.maxLead,
      showScoreDiff: exportView !== 'full' ? false : showScoreDiff,
      statOn,
      teamColors,
      awayColor,
      homeColor,
    },
  };
};
